import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import HomeHeader from "@/components/home/Home";
import Portfolio from "@/components/portfolio/Portfolio";
import About from "@/components/about/About";
import Skills from "@/components/skills/Skills";
import Contact from "@/components/contact/Contact";
import { personalInformations, projects, skills } from "../data/data.json";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (router.asPath == "/") {
      router.push("/#");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Selma Cokljat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeHeader data={personalInformations} />
        <Portfolio data={projects} />
        <About data={personalInformations} />
        <Skills data={skills} />
        <Contact />
      </main>
    </>
  );
}
