import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import Portfolio from "@/components/portfolio/Portfolio";
import About from "@/components/About";
import Services from "@/components/services/Services";
import Contact from "@/components/contact/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Selma Cokljat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header data={data.personalInformations} />
        <Portfolio />
        <About />
        <Services />
        <Contact />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/personal-website");
  const data = await res.json();

  return {
    props: { data },
    revalidate: 1,
  };
}
